# Generated by Django 3.2.5 on 2021-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anime_url', models.URLField(blank=True, verbose_name='Url')),
                ('anime_name', models.CharField(max_length=300, verbose_name='Nom')),
                ('anime_language', models.CharField(max_length=15, verbose_name='Langue')),
                ('anime_mean_rating', models.CharField(max_length=25, verbose_name='Note')),
                ('authors', models.CharField(max_length=300, verbose_name='Auteurs')),
                ('anime_type', models.CharField(max_length=300, verbose_name='Type')),
                ('anime_kind', models.CharField(max_length=300, verbose_name='Genre')),
                ('animation_studio', models.CharField(max_length=300, verbose_name="Studio d'animation")),
                ('year_of_production', models.CharField(max_length=300, verbose_name='Année de production')),
                ('n_episodes', models.CharField(max_length=300, verbose_name="Nombre d'épisodes")),
                ('status', models.CharField(max_length=300, verbose_name='Statut')),
                ('synopsis', models.TextField(blank=True, verbose_name='Synopsis')),
                ('collect_date', models.CharField(max_length=300, verbose_name='Date de collecte')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anime_url', models.URLField(blank=True, verbose_name="Url de l'animé")),
                ('episode_name', models.CharField(max_length=120, verbose_name='Nom')),
                ('episode_url', models.URLField(blank=True, verbose_name="Url de l'épisode")),
            ],
        ),
    ]
